import { checkFilePresence } from '../helpers';
import type { RuleInterface } from '../rule';

type Messages = 'presence';

const FILENAME = '.dockerignore';
const CONTENT = `# Generated by repo-linter

# Logs
logs
*.log

# Coverage
lib-cov
coverage

# NodeJs
build/Release
node_modules

# Others
.cache/
.circleci/
.eslintrc.*
.git/
.githooks/
.github/
.grunt
.npmrc
.nvmrc
.prettierignore
.prettierrc.*
.repolinterrc.*
.vscode
dist/
docs/
*.md
cypress/
**/.DS_Store
docker-compose.yml
*.tsbuildinfo`;

export const def: RuleInterface<Messages> = {
  name: 'base/require-dockerignore',

  docs: {
    description: `enforce the presence of a "${FILENAME}" file at root level`,
    url: 'https://github.com/algolia/repo-linter',
  },

  messages: {
    presence: `Expected file "${FILENAME}" to exists.`,
  },

  async exec(rule) {
    return await checkFilePresence(rule, {
      baseName: FILENAME,
      getContent: () => CONTENT,
    });
  },
};
