import { checkFilePresence } from '../helpers';
import type { RuleInterface } from '../rule';

type Messages = 'presence';

const FILENAME = '.eslintignore';
const CONTENT = `# Generated by repo-linter

dist/
node_modules/
.yarn/
.cache`;

export const rule: RuleInterface<Messages> = {
  name: 'base/require-eslintignore',

  docs: {
    description: `enforce the presence of a "${FILENAME}" file at root level`,
    url: 'https://github.com/algolia/repo-linter',
  },

  messages: {
    presence: `Expected file "${FILENAME}" to exists.`,
  },

  async exec({ fs, report }) {
    return await checkFilePresence(
      { fs, report },
      { baseName: FILENAME, getContent: () => CONTENT }
    );
  },
};
