import { checkFilePresence } from '../helpers';
import type { RuleInterface } from '../rule';

type Messages = 'presence';

const FILENAME = '.prettierignore';
const CONTENT = `# Generated by repo-linter

dist/
node_modules/
.yarn/
.cache`;

export const def: RuleInterface<Messages> = {
  name: 'base/require-prettierignore',

  docs: {
    description: `enforce the presence of a "${FILENAME}" file at root level`,
    url: 'https://github.com/algolia/repo-linter',
  },

  messages: {
    presence: `Expected file "${FILENAME}" to exists.`,
  },

  async exec(rule) {
    return await checkFilePresence(rule, {
      baseName: FILENAME,
      getContent: () => CONTENT,
    });
  },
};
