import { checkFilePresence } from '../../helpers';
import type { RuleInterface } from '../../rule';

type Messages = 'presence';

const FILENAME = '.gitignore';
const CONTENT = `# Generated by repo-linter
logs
*.log
coverage
*.lcov
node_modules/
jspm_packages/
*.tsbuildinfo
.npm
.eslintcache
.cache
.env
.env.test
.next
.nuxt


dist
.vuepress/dist
junit/
`;

export const def: RuleInterface<Messages> = {
  name: 'base/gitignore',

  docs: {
    description: `enforce the presence of a "${FILENAME}" file at root level`,
    url: 'https://github.com/algolia/repo-linter',
  },

  messages: {
    presence: `Expected file "${FILENAME}" to exists.`,
  },

  async exec(rule) {
    return await checkFilePresence(rule, {
      baseName: FILENAME,
      getContent: () => CONTENT,
    });
  },
};
