export const rulesets = {
  recommended: {
    'base/require-changelog': ['error', { extension: 'md' }],
    'base/require-contributingmd': ['error'],
    'base/require-dockerfile': ['error'],
    'base/require-dockerignore': ['error'],
    'base/require-envexample': ['error'],
    'base/require-eslintignore': ['error'],
    'base/require-eslintrc': ['error'],
    'base/require-gitignore': ['error'],
    'base/require-license': ['error', { extension: '' }],
    'base/require-nvmrc': ['error'],
    'base/require-packagejson': ['error'],
    'base/require-prettierrc': ['error'],
    'base/require-prettierignore': ['error'],
    'base/require-readmemd': ['error'],
    'base/require-releaseconfigjs': ['error'],
    'base/require-stylelintrcjson': ['error'],
    'base/require-renovate': ['error'],
    'base/require-tsconfigjson': ['error'],
  },
};
