export const rulesets = {
  recommended: {
    'base/require-changelog': ['error', { extension: 'md' }],
    'base/require-contributing': ['error', { extension: 'md' }],
    'base/require-dockerfile': ['error'],
    'base/require-dockerignore': ['error'],
    'base/require-envexample': ['error'],
    'base/require-eslintignore': ['error'],
    'base/require-eslintrc': ['error', { extension: '' }],
    'base/require-gitignore': ['error'],
    'base/require-license': ['error', { extension: '' }],
    'base/require-nvmrc': ['error'],
    'base/require-packagejson': ['error'],
    'base/require-prettierrc': ['error'],
    'base/require-prettierignore': ['error'],
    'base/require-readme': ['error', { extension: 'md' }],
    'base/require-releaserc': ['error', { extension: '' }],
    'base/require-stylelintrc': ['error', { extension: '' }],
    'base/require-renovaterc': ['error', { extension: '' }],
    'base/require-tsconfigjson': ['error'],
  },
};
